# Generated by Django 5.1.7 on 2025-04-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва іграшки')),
                ('description', models.TextField(blank=True, verbose_name='Опис іграшки')),
                ('price', models.DecimalField(decimal_places=2, default=19.99, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('gender', models.CharField(choices=[('M', 'Для хлопчиків'), ('F', 'Для дівчаток'), ('U', 'Універсальна')], default='U', max_length=1, verbose_name='Призначення')),
                ('age_group', models.CharField(default='3+', max_length=50, verbose_name='Вікова категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='toys/', verbose_name='Зображення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category', verbose_name='Категорія')),
            ],
        ),
    ]
